### ISSUE TITLE
Add CircleCI so we can compare with TravisCI

### ISSUE THREAD

**Issue by fc-boost** [StartupBoost/website#19]
https://circleci.com

**Comment by fc-boost** [comment]
https://hackernoon.com/continuous-integration-circleci-vs-travis-ci-vs-jenkins-41a1c2bd95f5

**Comment by MFCo** [comment]
TravisCI is better in our organization. The difference is about customization and paid plans. In addition CircleCI doesn't support Build Matrix. Therefore we decide to use TravisCI
